### ISSUE TITLE
Duplicate events and broadcasts

### ISSUE THREAD

**Issue by gsf** [wavefarm/api#23]
Events exported as broadcasts are still being exported as events as well, leading to duplicate items. See "Radius Sketchpad: Best of Sketchpad" records http://api.wavefarm.org/x4as67 (broadcast) and http://api.wavefarm.org/9nr8e3 (event) for an example.

**Comment by ptberry** [comment]
Possibly related and/or the same issue:
This event: https://wavefarm.org/api/svrata.
refers to related event https://wavefarm.org/api/5dnkn5. 
#5dnkn5 does not refer back to #svrata as expected. However duplicate broadcast https://wavefarm.org/api/m23764 does refer back to #svrata despite #svrata not referring to #m23764.

**Comment by gsf** [comment]
Believe this is fixed with new export handling of events and broadcasts.

**Comment by galenjosephhunter** [comment]
Just double-checking to make sure the duplicates currently present at
https://wavefarm.org/wgxc/schedule don't mean this is still an open issue...

On Fri, Apr 3, 2015 at 3:08 PM, Gabriel Farrell <notifications@github.com>
wrote:

> Believe this is fixed with new export handling of events and broadcasts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/api/issues/23#issuecomment-89393306>.
>



-- 
*Galen Joseph-Hunter  /  **Executive Director  /  Wave Farm*
Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 518-622-2598 (o) | 917-297-1537 (c)

Subscribe to our email announcements: http://eepurl.com/yRqVP
(Wave Farm is incorporated as free103point9 Inc.)
