### ISSUE TITLE
Broadcast Categories

### ISSUE THREAD

**Issue by ptberry** [wavefarm/api#30]
API results for broadcasts are returning arrays of numbers in the categories field instead of the expected text. For example:

https://wavefarm.org/api/8r9h4v

returns 

"categories":[18]

where something like this is returned for other types:

"categories":["free103point9 Transmission Art Event","WGXC: Hands-on Radio (90.7-FM) Event","Wave Farm Radio Event"]

**Comment by gsf** [comment]
Right you are. I've been meaning to fix this. Thanks for the issue.

**Comment by gsf** [comment]
Made unnecessary by #49.
