### ISSUE TITLE
Need Endpoint for Public "Add An Event" Saving

### ISSUE THREAD

**Issue by ptberry** [wavefarm/api#39]
Based on the existing form at http://wgxc.org/events, looks like the form should contain the following fields: 

email
event name
brief description
admission 
url
start date
end date
start time
end time

Required fields: email, event name, start date

Additional functionality:

1. Record should be saved with published = FALSE and category = "WGXC Community Event" (or similar)
2. Save should generate email to Wave Farm staff to alert them an event needs to be reviewed

**Comment by galenjosephhunter** [comment]
Current field is up at https://dev.wavefarm.org/wgxc/calendar. When a member of the public adds an event that content needs to be saved (without "public" checked) in admin and a notification email needs to be sent to info@wgxc.org with a link to the event in admin.

It would also be helpful to be able to look for all events that are not yet public, sorted by date. Is there a search url/string that can accomplish this? Something that can be added to?
https://dev.wavefarm.org/admin/?q=type%3Aevent+sites%3Awgxc

**Comment by gsf** [comment]
The full URL for non-public WGXC events by timestamp is https://dev.wavefarm.org/admin/?q=type%3Aevent%20sites%3Awgxc%20_missing_%3Apublic&sort=-timestamp.

**Comment by gsf** [comment]
Sounds good on the functionality side of submitting a new event. I'll have that up shortly.

**Comment by gsf** [comment]
@ptberry The endpoint allows you to populate any field in the event schema, but overrides public to false and categories to "WGXC Community Calendar Event". Let me know if you have any questions about that.

@galenjosephhunter It's currently set to deliver to your email address on both dev and prod for testing. I can change that to another address, or multiple addresses, when needed. It would also be possible to modify things later on so it sends email to all users or those with a particular role.

**Comment by galenjosephhunter** [comment]
Hi there,

Gabe thank you for working on this last night!

I just submitted a test event at https://wavefarm.org/wgxc/calendar, but
have not received any sort of email notification, nor can I locate the
event in admin. It doesn't appear to be present?

Galen

On Mon, May 18, 2015 at 3:49 AM, Gabriel Farrell <notifications@github.com>
wrote:

> @ptberry <https://github.com/ptberry> The endpoint allows you to populate
> any field in the event schema, but overrides public to false and categories
> to "WGXC Community Calendar Event". Let me know if you have any questions
> about that.
>
> @galenjosephhunter <https://github.com/galenjosephhunter> It's currently
> set to deliver to your email address on both dev and prod for testing. I
> can change that to another address, or multiple addresses, when needed. It
> would also be possible to modify things later on so it sends email to all
> users or those with a particular role.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/api/issues/39#issuecomment-102953324>.
>



-- 
*Galen Joseph-Hunter  /  **Executive Director  /  Wave Farm*
Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 518-622-2598 (o) | 917-297-1537 (c)

Subscribe to our email announcements: http://eepurl.com/yRqVP
(Wave Farm is incorporated as free103point9 Inc.)

**Comment by ptberry** [comment]
There is still a little work on the front end now to enable this - will get to it later today.

**Comment by galenjosephhunter** [comment]
Ah! okay. keep me posted and I can test when appropriate.

On Mon, May 18, 2015 at 10:37 AM, Peter Berry <notifications@github.com>
wrote:

> There is still a little work on the front end now to enable this - will
> get to it later today.
>
>
>
>
> > On May 18, 2015, at 3:01 AM, Galen Joseph-Hunter <
> notifications@github.com> wrote:
> >
> > Hi there,
> >
> > Gabe thank you for working on this last night!
> >
> > I just submitted a test event at https://wavefarm.org/wgxc/calendar, but
> > have not received any sort of email notification, nor can I locate the
> > event in admin. It doesn't appear to be present?
> >
> > Galen
> >
> > On Mon, May 18, 2015 at 3:49 AM, Gabriel Farrell <
> notifications@github.com>
> > wrote:
> >
> > > @ptberry <https://github.com/ptberry> The endpoint allows you to
> populate
> > > any field in the event schema, but overrides public to false and
> categories
> > > to "WGXC Community Calendar Event". Let me know if you have any
> questions
> > > about that.
> > >
> > > @galenjosephhunter <https://github.com/galenjosephhunter> It's
> currently
> > > set to deliver to your email address on both dev and prod for testing.
> I
> > > can change that to another address, or multiple addresses, when
> needed. It
> > > would also be possible to modify things later on so it sends email to
> all
> > > users or those with a particular role.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/wavefarm/api/issues/39#issuecomment-102953324>.
> > >
> >
> >
> >
> > --
> > *Galen Joseph-Hunter / **Executive Director / Wave Farm*
> > Transmission Arts, WGXC 90.7-FM, Media Arts Grants
> > 5662 Route 23 Acra, NY 12405 518-622-2598 (o) | 917-297-1537 (c)
> >
> > Subscribe to our email announcements: http://eepurl.com/yRqVP
> > (Wave Farm is incorporated as free103point9 Inc.)
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/api/issues/39#issuecomment-103081554>.
>



-- 
*Galen Joseph-Hunter  /  **Executive Director  /  Wave Farm*
Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 518-622-2598 (o) | 917-297-1537 (c)

Subscribe to our email announcements: http://eepurl.com/yRqVP
(Wave Farm is incorporated as free103point9 Inc.)
