### ISSUE TITLE
Dedicated endpoint for "Featured" WGXC Broadcasts and Events

### ISSUE THREAD

**Issue by ptberry** [wavefarm/api#40]
Needed to drive WGXC home page gallery. 

Notes:

1. The endpoint should return up to 10 broadcasts and/or events marked as featured but not yet expired. Items currently ongoing (start date <= now <= end data) should be included.
2. Items should be sorted by start date, start time (?).
3. Fields to be returned (not all fields exist for both events and broadcasts but the following is desired information for the image captions):
item id
item type
name (main)
start date
start time
end date
end time
brief description
show name
location
image URL
image credit

**Comment by gsf** [comment]
Do we really need all those fields returned? I thought we were introducing a "caption" field for broadcasts and events that would only be used when featured. And if dates and times are already factored into what's returned and how they're sorted, this would be all that should need to be returned:
- id
- image url
- image credit
- caption

**Comment by galenjosephhunter** [comment]
“Caption” is really the display of Calendar or Broadcast Title + Date.
Image URL is needed
Image Credit is needed
I assume ID is needed to facilitate linking to the Calendar or Broadcast page, right?

**Comment by gsf** [comment]
Oh, so we don't need a caption field because we'll just use name and date?

And yes, ID is needed for linking back to the item. We'll need type as well to know what should precede the ID in the link URL.

**Comment by galenjosephhunter** [comment]
That's my understanding.

**Comment by gsf** [comment]
Okay then I'll return name, start date, start time, end date, and end time and we can choose how to format the dates in the client.

**Comment by ptberry** [comment]
Sounds like this is sorted, but for the record those fields were based on this received spec:

Featured Broadcast Caption info:
Show Name: Broadcast Name
Date Time

Featured Calendar Event Caption info:
Calendar Event Name
Location
Date Time

**Comment by ptberry** [comment]
I neglected to mention this issue in the commit, but it's closed by [3ea6899](https://github.com/wavefarm/api/commit/3ea68990fcff1c3619792de7f76e4dadc9ab8abe) and [f01cbd7](https://github.com/wavefarm/api/commit/f01cbd7ff3099a5d4ab723a1771b3febb3c7cd07) .

**Comment by gsf** [comment]
Sweet. I'll review when I get a chance.
