### ISSUE TITLE
Search not returning event when filtering by date

### ISSUE THREAD

**Issue by ptberry** [wavefarm/api#48]
This event:

https://dev.wavefarm.org/admin/dc2y4w

has a start date of 2014-09-13 but is not returned by the search api when filtering by that date. This is true in both the archive and calendar on the front end. For instance in the archive [this](https://dev.wavefarm.org/archive?q=%22groundswell%202014%22%20sites%3Awgxc%20type%3Aevent&date=&date2=) returns the event, current result #10, but [this](https://dev.wavefarm.org/archive?q=%22groundswell%202014%22%20sites%3Awgxc%20type%3Aevent&date=2014-09-13&date2=) does not.

The actual api URL used by the calendar page is [here](https://dev.wavefarm.org/api/search?q=type:event%20sites:wgxc&sort=start&date=2014-09-13) and is missing the event.

**Comment by gsf** [comment]
With the new export this should be fixed. Is that true, @ptberry?

**Comment by ptberry** [comment]
Yep, looks like it. I'll go ahead on close this.
