### ISSUE TITLE
TA add an event to notify info@wavefarm.org

### ISSUE THREAD

**Issue by ptberry** [wavefarm/api#70]
https://github.com/wavefarm/api/blob/master/routes/wgxc/add-event.js needs to send email alerts to info@wavefarm.org when incoming event is a TA event. Front end code already passes a "source" field as part of the form to distinguish wgxc or ta and the endpoint already uses "source" to set the proper sites and categories fields. Endpoint should use "source" to determine proper email as well.

@gsf : Since the wgxc email is passed as an environment variable I wasn't sure how you wanted to handle this. Happy to pass a marker to mail() function, or even pass the hardcoded emails, or to conditionally call a different mail() method for /ta.

**Comment by gsf** [comment]
I dropped the environment variable and added a parameter to mail(). Looks good?

Also, since it's no longer a wgxc-specific endpoint, the file should be moved up to `routes/` and the endpoint should be `/add-event` instead of `/wgxc/add-event`.

**Comment by ptberry** [comment]
Looks good to me, thanks.

**Comment by gsf** [comment]
Made way for wavefarm/site#187.
